
export const FETCH_HERO_SUCCESS = 'FETCH_HERO_SUCCESS'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const CUSTOM_GREETING = 'CUSTOM_GREETING'
export const FETCH_HERO_LOADING = 'FETCH_HERO_LOADING'
export const FETCH_HERO_ERROR = 'FETCH_HERO_ERROR'